author,updated_at,like_count,text,public
@toglannestor400,2021-01-07T15:26:41Z,0,"Thanks for the example, it helped me a lot, but then I would now like to have for each column a list of dates whose maximum date (2010-05-27) and a minimum date (2008-05-20) well respected in the interval of the two dates and for each column there may be a different date interval, your help will be very useful thank you!",True
@user-fv2gm5vs6e,2019-11-23T11:58:03Z,0,how to export specific  columns from df to csv file,True
@davidwalker575,2019-10-31T21:40:55Z,1,This guy makes more mistakes while typing than my mom!,True
@arifulislamistiak7234,2019-07-09T17:52:44Z,0,thanks dude,True
@chloekimball536,2019-02-22T12:47:30Z,0,you are my saviour,True
@allaboutpixhawkandrpi3691,2018-12-16T18:59:36Z,0,is there a way to change the order of columns or rows?,True
@harikrishhna,2018-12-05T22:37:17Z,0,How do I concatenate two columns? Thanks.,True
@akirabanerjee8084,2018-06-20T22:12:02Z,0,How do we add a new empty column in pandas?,True
@quahbt357,2018-06-15T15:03:59Z,0,Fuck you,True
@anmolhaque7510,2018-04-08T17:04:08Z,0,"having this error while trying to do column. manipulation Traceback (most recent call last):   File ""/Applications/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py"", line 658, in na_op     raise_on_error=True, **eval_kwargs)   File ""/Applications/anaconda3/lib/python3.6/site-packages/pandas/core/computation/expressions.py"", line 211, in evaluate     **eval_kwargs)   File ""/Applications/anaconda3/lib/python3.6/site-packages/pandas/core/computation/expressions.py"", line 122, in _evaluate_numexpr     result = _evaluate_standard(op, op_str, a, b, raise_on_error)   File ""/Applications/anaconda3/lib/python3.6/site-packages/pandas/core/computation/expressions.py"", line 64, in _evaluate_standard     return op(a, b) TypeError: unsupported operand type(s) for -: 'str' and 'float'  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File ""/Applications/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py"", line 682, in safe_na_op     return na_op(lvalues, rvalues)   File ""/Applications/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py"", line 664, in na_op     result[mask] = op(x[mask], _values_from_object(y[mask])) TypeError: unsupported operand type(s) for -: 'str' and 'float'  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File ""sim_1.py"", line 14, in <module>     bed_elev['t0-t1'] = bed_elev['t0']- bed_elev['t1']   File ""/Applications/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py"", line 721, in wrapper     result = wrap_results(safe_na_op(lvalues, rvalues))   File ""/Applications/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py"", line 692, in safe_na_op     lambda x: op(x, rvalues))   File ""pandas/_libs/algos_common_helper.pxi"", line 1212, in pandas._libs.algos.arrmap_object   File ""/Applications/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py"", line 692, in <lambda>     lambda x: op(x, rvalues)) TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')",True
@bulevishal2299,2018-03-21T08:27:09Z,0,How to read google sheet  using pd.read_csv(google drive csv) ?,True
@yoco8041,2017-09-09T19:37:07Z,0,How can I Replace Strings based on column number in CSV? I mean if the value is 0 in column 2 i need to replace it with null?,True
@kannu5039,2017-03-14T15:45:45Z,0,Is it possible to replace the date as 1 for ex if i have frequent dates like  dates 08/05/1996 08/05/1996 08/05/1996 09/05/1994 10/05/1998 i want to replace it with 1 like this 1 1 1 2 3,True
@andrewso9798,2016-12-09T14:31:40Z,0,"Thanks sentdex, your tutorials are clear, concise, and very informative.",True
@octavianmorcov3093,2016-11-29T17:45:43Z,0,"Finally I found something properly explained, step-by-step with example. Thanks",True
@mamunurrashid5652,2016-09-06T15:31:39Z,0,"What if I wanted to add stock symbol in a column of the csv file with other columns like ""Date,Open,High,Low,Close,Vol""......?",True
@Marlombrei1,2016-01-18T23:33:14Z,0,do it before: df4 = df3.copy()  all the rest will work,True
@asneogy,2015-10-12T06:13:27Z,3,"hey! I think for the column rename, if you dodf= df.rename(columns= {'col1_old' : 'col1_new'} )it does not give the warning any more!",True
@uniqueraj518,2015-07-20T22:34:27Z,2,"nice tutorial if you use df4.loc[:,""CLOSE""]=df3.rename(columns={'Close':'CLOSE'}, inplace = True)  you will get rid of this warning, it is actually due to indexing issue when you want to assign the part of pandas dataframe to another dataframe as a slice",True
@JakeWong19,2015-05-30T16:10:17Z,0,"I was wondering, at the last part of your video when you are talking about df4 = df3[(df3['CLOSE'] > 1400)],     are you able to filter by 2 columns? Like for eg: having what you wrote, and 'OPEN' > 1300?   might it be possible?",True
@olaalsonosy5663,2015-03-02T11:32:54Z,0,but the first error is still confusing me,True
@olaalsonosy5663,2015-03-02T11:32:29Z,0,"im sorry , i realized ..im so stupid Open is the field name ,,,,  my mistake",True
@olaalsonosy5663,2015-03-02T10:53:47Z,0,"Also when i do the df2 = df. ['Open'] command it gives me this error Traceback (most recent call last):   File ""C:/Python27/interpolation.py"", line 7, in <module>     df2 = df['Open']   File ""C:\Python27\lib\site-packages\pandas\core\frame.py"", line 1780, in __getitem__     return self._getitem_column(key)   File ""C:\Python27\lib\site-packages\pandas\core\frame.py"", line 1787, in _getitem_column     return self._get_item_cache(key)   File ""C:\Python27\lib\site-packages\pandas\core\generic.py"", line 1068, in _get_item_cache     values = self._data.get(item)   File ""C:\Python27\lib\site-packages\pandas\core\internals.py"", line 2849, in get     loc = self.items.get_loc(item)   File ""C:\Python27\lib\site-packages\pandas\core\index.py"", line 1402, in get_loc     return self._engine.get_loc(_values_from_object(key))   File ""pandas\index.pyx"", line 134, in pandas.index.IndexEngine.get_loc (pandas\index.c:3807)   File ""pandas\index.pyx"", line 154, in pandas.index.IndexEngine.get_loc (pandas\index.c:3687)   File ""pandas\hashtable.pyx"", line 696, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12310)   File ""pandas\hashtable.pyx"", line 704, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12261) KeyError: 'Open'",True
@olaalsonosy5663,2015-03-02T10:51:52Z,0,and when i change the column name to any column name in my file it runs correctly,True
@olaalsonosy5663,2015-03-02T10:51:00Z,0,"im trying to read from csv file and it gives me this error Traceback (most recent call last):   File ""C:/Python27/interpolation.py"", line 5, in <module>     df=pd.read_csv('D:\DATA SETS\MY 4SQ DATA SET\Texas.csv',index_col='vid')   File ""C:\Python27\lib\site-packages\pandas\io\parsers.py"", line 465, in parser_f     return _read(filepath_or_buffer, kwds)   File ""C:\Python27\lib\site-packages\pandas\io\parsers.py"", line 251, in _read     return parser.read()   File ""C:\Python27\lib\site-packages\pandas\io\parsers.py"", line 710, in read     ret = self._engine.read(nrows)   File ""C:\Python27\lib\site-packages\pandas\io\parsers.py"", line 1212, in read     index, names = self._make_index(data, alldata, names)   File ""C:\Python27\lib\site-packages\pandas\io\parsers.py"", line 877, in _make_index     index = self._get_simple_index(alldata, columns)   File ""C:\Python27\lib\site-packages\pandas\io\parsers.py"", line 911, in _get_simple_index     i = ix(idx)   File ""C:\Python27\lib\site-packages\pandas\io\parsers.py"", line 905, in ix     raise ValueError('Index %s invalid' % col) ValueError: Index vid invalid",True
