author,updated_at,like_count,text,public
@Bidek56,2020-09-30T00:29:23Z,3,"Running everything as root, strong security, Texas style!!ðŸ˜‚",True
@carrillocca,2020-08-12T06:38:18Z,0,"First,, Thank you so much for your videos. They have been very helpful for me. I wanto ask if it is possible to install opencv on the virtual machine, I keep getting an error. Is it because is python 2.7?",True
@charleslondon9900,2020-08-05T13:05:51Z,0,Great tutorial; but you are so heavy on your keyboard it hurts my ear as I am listening on headphones.,True
@reebosauruz,2020-05-26T01:18:06Z,0,Do you know if there is a way in python to set the minimum and maximum results? I was pretty surprised how uninformed the documentation can be...=/,True
@kunal9999100,2020-01-02T17:51:24Z,0,"I want to try Google API for two months? Will, it cost me any money?",True
@pypro,2019-09-25T01:10:51Z,1,Dude for real mate hahaha evey question I have you already solve it !!,True
@harikishorep8778,2019-05-21T07:05:53Z,0,@HarrisonKinsley can you please tell me which linux distro you are using ?,True
@eceaslar2883,2019-03-29T12:19:16Z,2,"Hey great Video thanks, but for the new comers: vision modul is not support Client anymore, use ImageAnnotatorClient()",True
@mohdanaskhan7203,2019-03-19T06:00:31Z,2,"Why didn't you add your photo? Even you knew that It would say ""Senior Citizen"" xD",True
@mohammedtahseen8883,2019-03-08T19:51:27Z,0,Thanks you for the video.can you do the same with nodejs on data labeling.,True
@kevinshah9395,2019-03-08T14:11:36Z,0,I am having problem in setting up billing account please help,True
@kevinshah9395,2019-02-25T09:57:11Z,0,Do we need to add billing account before using credentials??,True
@LicinusLucullus,2019-02-13T19:21:01Z,0,I am a big fan of sentdex but this was pretty poor stuff. How about putting some documents or tables in and massaging the data or something,True
@anuragchoudhary1,2019-01-16T15:56:02Z,1,Just a tip :  CTRL + Insert for Copy and Shift + Insert for Paste. Shift + Insert works every where!,True
@Mahesh-gq7fm,2018-12-27T12:06:49Z,0,"I encounter with the following error   File ""vision_ex1.py"", line 5, in <module>     vision_client = vision.Client() AttributeError: 'module' object has no attribute 'Client' Someone help me",True
@carlossegura403,2018-12-09T19:51:55Z,0,google doesn't have the best documentation,True
@multithread,2018-11-17T08:16:39Z,1,no module named google.cloud -___-,True
@DavidDrakHaker,2018-10-30T20:58:10Z,0,"help :/  PermissionDenied: 403 This API method requires billing to be enabled. Please enable billing on project #216590715706 by visiting https://console.developers.google.com/billing/enable?project=216590715706 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.",True
@mallusreddy,2018-10-09T07:27:00Z,0,It's really nice tutorial.. Sir can guide me how to it for speech,True
@fuckedup610,2018-08-24T12:57:34Z,1,"If you guys are working with different os and want to make that GOOGLE_APPLICATION_CREDENTIALS work without any incompatibility issue you can do something like this in your program:   import os os.environ[""GOOGLE_APPLICATION_CREDENTIALS""] = ""path_to_your_.json_credential_file""",True
@rahulraman1537,2018-08-16T09:37:33Z,0,"Hi,  I've followed your tutorial but I'm getting Serviceunavailable: 503 name resolution failure error. Please help.",True
@bhuvaneshs.k638,2018-07-11T12:01:05Z,0,Can u do a complete tutorial on Google's Tesseract OCR for Linux.... Like evrythng... To use trained LSTM models frm GitHub and all thoz stuffs...,True
@Wrathos,2018-06-16T14:02:30Z,0,"""File ""visionex.py"", line 19 SyntaxError: Non-ASCII character '\xef' in file visionex2.py on line 19, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details"" Anyone got this errormsg and found a fix?",True
@avinashsinha1206,2018-05-07T05:34:56Z,0,"I am getting an error as : ""AttributeError: 'module' object has no attribute 'Client"".  I tried running ""sudo pip install --upgrade google-cloud-vision"". But it was of no help. Can you tell me what I am missing over here?",True
@nadnad2698,2018-05-06T08:35:47Z,3,"hello it's my first time doing this kind of stuff. i've never use any of linux-kind code before, but when i try to install python-pip it won't install and keep saying unable to locate package python-pip. i following every step of this video since part 1 but maybe there's something i didn't know that isn't in this video. maybe someone can help me please? thank you btw that's a good video",True
@chapaya100,2018-05-05T13:16:27Z,0,i got this error :  google.api_core.exceptions.PermissionDenied: 403 Request had insufficient authentication scopes.,True
@yiwei9184,2018-04-29T19:24:04Z,0,Thank you for this great video!,True
@bijinregipanicker6916,2018-03-28T10:31:37Z,0,how to do it in windows pc ?,True
@PocketJumper,2018-03-17T18:32:36Z,0,"i am getting this weird error when trying to run the visionex.py  ERROR:root:AuthMetadataPluginCallback ""<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7ff40c1427d0>"" raised exception! Traceback (most recent call last):   File ""/usr/local/lib/python2.7/dist-packages/grpc/_plugin_wrapping.py"", line 77, in __call__     callback_state, callback))   File ""/usr/local/lib/python2.7/dist-packages/google/auth/transport/grpc.py"", line 77, in __call__     callback(self._get_authorization_headers(context), None)   File ""/usr/local/lib/python2.7/dist-packages/google/auth/transport/grpc.py"", line 65, in _get_authorization_headers     headers)   File ""/usr/local/lib/python2.7/dist-packages/google/auth/credentials.py"", line 121, in before_request     self.refresh(request)   File ""/usr/local/lib/python2.7/dist-packages/google/auth/compute_engine/credentials.py"", line 96, in refresh     six.raise_from(new_exc, caught_exc)   File ""/usr/lib/python2.7/dist-packages/six.py"", line 718, in raise_from     raise value  anyone an idea was is wrong?",True
@AlejandroVazquez-yh4hx,2018-03-16T04:18:05Z,0,"hi Traceback (most recent call last):   File ""vision_labels.py"", line 4, in <module>     vision_client = vision.Client() AttributeError: 'module' object has no attribute 'Client'",True
@RaunakJoshi,2018-03-03T10:21:15Z,0,Sentdex. Windows version please. API configuration seems a tough job. Reply expected.,True
@SubhamMahato39,2018-03-02T08:26:33Z,0,how to access this API on my local machine and not the virtual machine on google cloud,True
@daudshaikh4146,2018-02-22T16:58:37Z,0,"File ""visionex.py"" line 4,  in <module> vision_client = vision.Client () AttributeError: 'module' object has no attribute 'Client'  Plz help me",True
@wolfgangplato8593,2018-02-21T13:55:01Z,0,I have a python script on my local machine which uses a lot of computing power. All I want to do is move the computing part the google cloud. Can anyone help me with this problem|?,True
@junkmail75034,2018-02-09T22:11:52Z,4,"Thanks for this post. A lot of changes has occurred at API level. I have to make some changes in order to make it work. Here is my visionex.py:  import io from google.cloud import vision from google.cloud.vision import types vision_client = vision.ImageAnnotatorClient() file_name = 'kimberly-guilfoyle-2.jpg' with io.open(file_name,'rb') as image_file:     content = image_file.read()     image = types.Image(content=content) response = vision_client.label_detection(image=image) labels = response.label_annotations for label in labels:     print(label.description, label.score)   root@nlp1:~/gcloudstuff/visionex# python visionex.py  (u'hair', 0.9773183465003967) (u'eyebrow', 0.9387233257293701) (u'human hair color', 0.9043058753013611) (u'beauty', 0.8982101678848267) (u'chin', 0.8967102766036987) (u'hairstyle', 0.8900614976882935) (u'long hair', 0.8221617937088013) (u'forehead', 0.8207109570503235) (u'layered hair', 0.7995803952217102) (u'black hair', 0.7725696563720703)",True
@johnpolaai8181,2018-02-06T11:11:54Z,0,"error_remapped_callable     six.raise_from(exceptions.from_grpc_error(exc), exc)   File ""<string>"", line 3, in raise_from google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: 'dict' object has no attribute 'before_request'",True
@sahilchhabra9421,2018-02-04T06:38:37Z,0,"Hi , please confirm python programming knowledge is required for google cloud. i have no much idea about google cloud and my programming knowledge is zero.",True
@ninichurch6449,2018-01-30T16:40:53Z,0,really want to know how to use google vision api to detect texts of a screenshot,True
@SkrollrBeats,2018-01-16T15:13:03Z,0,you use spaces,True
@mohanakrishnavh9988,2018-01-16T06:01:37Z,2,"@sentdex I am getting the below error: root@machine1:~/gcloud/visionex# python vision.py Traceback (most recent call last):   File ""vision.py"", line 4, in <module>     vision_client = vision.Client() AttributeError: 'module' object has no attribute 'Client'  How to fix this?",True
@RafaelSales55,2018-01-02T04:34:05Z,3,"File ""visionex.py"", line 2, in <module>     from google.cloud import vision ImportError: cannot import name vision",True
@mohamedazharudeenm7109,2017-12-30T08:39:02Z,0,"hello sir ,i just done as like you said but iam getting attribute error can you please help .what will be a problem",True
@aliibrahim5428,2017-12-28T14:39:39Z,0,"I'm getting this error ... File ""visionex.py"", line 2, in <module>     from google.cloud import vision ImportError: cannot import name vision",True
@michelkant,2017-12-07T23:12:44Z,5,"Hey all, anybody got this running with conda in a virtualenv? I'm having problems even finding the package for the google-cloud =/",True
@ronakkumar1934,2017-11-25T10:38:12Z,0,is it a paid service,True
@100dollerbill4,2017-11-20T08:29:54Z,0,'Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service    pls hep me out i am gettign this error,True
@getsglobalengineering7723,2017-11-14T05:42:36Z,0,"on running python visionex.py, I get this error  raceback (most recent call last):   File ""visionex.py"", line 11, in <module>     labels =  image.detect_labels()   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/vision/image.py"", line 219, in detect_labels     annotations = self.detect(features)   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/vision/image.py"", line 143, in detect     return self._detect_annotation(images)   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/vision/image.py"", line 117, in _detect_annotation     return self.client._vision_api.annotate(images)   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/vision/_gax.py"", line 69, in annotate     responses = annotator_client.batch_annotate_images(requests).responses   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/vision_v1/gapic/image_annotator_client.py"", line 171, in batch_annotate_images     return self._batch_annotate_images(request, options)   File ""/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py"", line 452, in inner     return api_caller(api_call, this_settings, request)   File ""/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py"", line 438, in base_caller     return api_call(*args)   File ""/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py"", line 376, in inner     return a_func(*args, **kwargs)   File ""/usr/local/lib/python2.7/dist-packages/google/gax/retry.py"", line 127, in inner     ' classified as transient', exception) google.gax.errors.RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Request had insufficient authentication scopes.)>)",True
@techsolution7370,2017-11-03T09:53:16Z,0,Is it paid for enabling the api ?,True
@chanchal11,2017-10-23T06:27:09Z,0,Thank you. Your videos help a lot to learn  every new stuffs coming around.,True
@tonycheung5055,2017-10-22T23:43:11Z,0,new description:  glasses professional facial hair smile profession fun Â  LOL,True
@anitasancho5886,2017-09-27T22:07:31Z,0,"Whe I ran python visionex.py I get ths error:  File ""/usr/local/lib/python2.7/dist-packages/google/auth/compute_engine/credentials.py"", line 93, in refresh     raise exceptions.RefreshError(exc) RefreshError: ('Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\n<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=""initial-scale=1, minimum-scale=1, width=device-width"">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:**#fff**;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/computeMetadata/v1/instance/service-accounts/default/?recursive=true</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n', <google.auth.transport.requests._Response object at 0x7f8c9dd17e90>) )>)",True
@akhilsoni4109,2017-09-20T16:03:50Z,0,Can anyone help me with this? I am getting this error: RefreshError: ('Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 I am unable to figure out how to resolve this,True
@nasirrahim5610,2017-09-18T01:00:33Z,0,"i am getting this error. could someone help me in this   Traceback (most recent call last):   File ""visionex.py"", line 5, in <module>     vision_client = vision.Client()   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/vision/client.py"", line 80, in __init__     project=project, credentials=credentials, _http=_http)   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/client.py"", line 211, in __init__     _ClientProjectMixin.__init__(self, project=project)   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/client.py"", line 165, in __init__     project = self._determine_default(project)   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/client.py"", line 178, in _determine_default     return _determine_default_project(project)   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/_helpers.py"", line 179, in _determine_default_project     _, project = google.auth.default()   File ""/usr/local/lib/python2.7/dist-packages/google/auth/_default.py"", line 281, in default     credentials, project_id = checker()   File ""/usr/local/lib/python2.7/dist-packages/google/auth/_default.py"", line 142, in _get_explicit_environ_credentials     os.environ[environment_vars.CREDENTIALS])   File ""/usr/local/lib/python2.7/dist-packages/google/auth/_default.py"", line 72, in _load_credentials_from_file     'File {} is not a valid json file.'.format(filename), exc) google.auth.exceptions.DefaultCredentialsError: ('File /root/gcloudstuff/apikey.json is not a valid json file.', ValueError('Invalid control character at: line 5 column 37 (char 167)',))",True
@arycloud2924,2017-08-20T05:47:26Z,0,"Hi sentdex, thanks for these videos, very helpful.                         I need your help: I need to create a project on google cloud via Google cloud API Python client, I'm trying to do this by using resource manager API but not get any success, how can I create a GCP project through API? For detail take a look at this : https://stackoverflow.com/q/45071026/7644562  ,  Â help me, please!",True
@guitarpikstar,2017-07-28T13:10:02Z,0,"Hey great video, but my Raspberry Pi says:  import google.auth.credentials ImportError: No module named auth.credentials  Could someone help, please?",True
@IamLahiruW,2017-07-21T19:14:43Z,0,When i try to execute visionex.py getting following error   IOError: [Errno 2] No such file or directory: '/root/gcloudstaff/apikey.json',True
@RutvikPatel2611,2017-07-12T11:12:36Z,0,"raise exceptions.DefaultCredentialsError(_HELP_MESSAGE) google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credential and re-run the application. For more information, please see https://developers.google.com/accounts/docs/application-default-credentials.  please help this kind of error while running the python scrpit",True
@theAnon1983,2017-07-11T17:59:37Z,0,"Thank you so much for this tutorial! Do you know if it's possible to upload 10K images instead of a single image? Your script in 9:20 is a good starting point, but how one will go about doing this if the folder contains more than one images?",True
@suhailrifky3850,2017-06-29T05:25:30Z,1,why is all ur tutorials on python?why not java,True
@lunchtimemilkbag,2017-06-26T15:18:38Z,0,Thanks so much!,True
@nandinisaini1313,2017-06-21T07:22:52Z,0,"I am getting these errors : please help me to solve these errors. Traceback (most recent call last):   File ""/home/nandini/gcloudstuff/visionex/visionex.py"", line 2, in <module>     from google.cloud import vision   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/vision/__init__.py"", line 21, in <module>     from google.cloud.vision.client import Client   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/vision/client.py"", line 22, in <module>     from google.cloud.vision._gax import _GAPICVisionAPI   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/vision/_gax.py"", line 17, in <module>     from google.cloud.gapic.vision.v1 import image_annotator_client   File ""/usr/local/lib/python2.7/dist-packages/google/cloud/gapic/vision/v1/image_annotator_client.py"", line 31, in <module>     from google.gax import api_callable   File ""/usr/local/lib/python2.7/dist-packages/google/gax/__init__.py"", line 42, in <module>     from google.gax.errors import GaxError   File ""/usr/local/lib/python2.7/dist-packages/google/gax/errors.py"", line 34, in <module>     from google.gax import config   File ""/usr/local/lib/python2.7/dist-packages/google/gax/config.py"", line 34, in <module>     from google.gax import grpc   File ""/usr/local/lib/python2.7/dist-packages/google/gax/grpc.py"", line 36, in <module>     from google.gax import _grpc_google_auth   File ""/usr/local/lib/python2.7/dist-packages/google/gax/_grpc_google_auth.py"", line 39, in <module>     import google.auth.transport.requests   File ""/usr/local/lib/python2.7/dist-packages/google/auth/transport/requests.py"", line 22, in <module>     import requests   File ""/usr/local/lib/python2.7/dist-packages/requests/__init__.py"", line 84, in <module>     from urllib3.contrib import pyopenssl   File ""/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py"", line 46, in <module>     import OpenSSL.SSL   File ""build/bdist.linux-x86_64/egg/OpenSSL/__init__.py"", line 8, in <module>   File ""build/bdist.linux-x86_64/egg/OpenSSL/SSL.py"", line 113, in <module> AttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST \'",True
@tronicway1,2017-06-19T14:36:56Z,0,"Thank you a lot for this, I was lost of how to begin (:",True
@ouyajam,2017-06-17T02:53:57Z,0,"that export env var saved my life, much appreciated!",True
@maersk86,2017-06-15T10:31:30Z,0,"could anyone help me with this error:  StatusCode.PERMISSION_DENIED, Request had insufficient authe ntication scopes",True
@sannymunn1471,2017-05-28T21:55:23Z,0,"omg , I dont mean to be but I am those programmer. I see you used space instead of tab. Sorry, I have no life",True
@mitchelscareer6631,2017-05-22T14:34:22Z,0,"Sir, perfect video. Google's API are quite popular atm but little good tutorials exist on the internet. As Google's documentation is complete but also very technical, this tutorial is exceptionally handy. Thanks.",True
@pujanjain7757,2017-05-19T09:50:48Z,0,"Hi thanks for this video.. nice info..  I have a query.. I am running google cloud for java. (calling simple compute API to list all the instances). When I execute this from out of my office, it runs properly. But when I execute it from within the company premises, it gives ""SSLException error"". So is there any setting if you are aware of to add proxy setting ?",True
@rovo3199,2017-05-07T18:29:47Z,0,I did exactly what you did in the video but I'm getting this error:Â google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials.,True
@nwayyananthlaing911,2017-05-04T06:45:28Z,0,Thanks.,True
@donaldli4755,2017-04-29T22:51:18Z,0,Really helpful! Thanks! A lot of the stuff regarding that on Youtube right now is out of date so GREAT THANKSSSS!,True
@rankala,2017-04-25T09:38:24Z,0,hey :-) i tried to install pip on gcloud but i get an error and  i dont know what to do. I copied this https://pastebin.com/Pdyt5n5j  hopefuly you can help me,True
@SwamyYmln,2017-04-09T22:34:59Z,0,"Hi when i am trying to run the code i am getting the following error Kindly let me know where i might have made mistake.  google.gax.errors.RetryError: GaxError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Request had insufficient authentication scopes.)>)",True
@snpsforyomom,2017-03-30T07:17:35Z,0,silly question but is the virtual machine required to use these Google APIs?,True
@marcleonard4593,2017-03-29T15:55:28Z,0,"As far as the coordinates of the labels, is that what this might be: https://cloud.google.com/vision/docs/reference/rest/v1/images/annotate#BoundingPoly",True
@crowdquest1203,2017-03-25T20:14:49Z,0,isnt locations supposed to  be gps coordinates (if included in photo metadata)?,True
@binksbiz8911,2017-03-25T13:09:56Z,2,"getting error message while executing the code: ""'File {} is not a valid json file.'.format(filename), exc) google.auth.exceptions.DefaultCredentialsError: ('File /root/gcloudstuff/apikey.json is not a valid json file.', ValueError('Invalid control character at: line 5 column 38 (char 173)',))"" - my file looks similar to the one in the video... enabled api...not sure what's wrong..",True
@kipsta1993,2017-03-23T20:07:29Z,0,haha i was like sitting asking myself how creating vision folder is enough for gcloud to know which api is needed,True
@aitorplaza2560,2017-03-22T11:07:33Z,0,"Hi!  I have a question, why ""print()"" function works if you are using python 2.7?",True
@ApplySkills,2017-03-22T02:15:35Z,1,do you think 'location' might be the meta data embedded within the image?,True
@douglasfletcher6609,2017-03-21T21:04:39Z,10,ha senior citizen classic,True
@benilev6511,2017-03-21T20:12:19Z,0,"1 - Why are you running as root? 2 - Maybe the ""bounds"" field of the label gives you the bounding box of the item in the image?",True
@beckettman42,2017-03-21T17:55:39Z,2,"Does anybody know if it is possible to run the API from a local machine.  I have an Ubuntu machine with tensorflow-GPU and google cloud installed.    I have created a project in google cloud, generated a key and enabled vision but I get ""Could not automatically determine credentials.""    Is what I'm trying to do possible or am I making a stupid error?  I answered my own question by actually reading the link that comes with the error.  :p  Follow the instructions the instructions in the above video until you have input the path for the key and then:  Install Google Cloud SDK on your machine: https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu  Run 'gcloud auth application-default login' in a terminal and a browser window will come up asking you to sign your life away to google-ai.  Then your machine should be authorized to use the API.   Great Video and happy computing.",True
@Graymobojogo,2017-03-21T16:23:30Z,1,Could locations be geolocation?  https://cloud.google.com/blog/big-data/2016/09/around-the-world-landmark-detection-with-the-cloud-vision-api,True
@amitsangwan007,2017-03-21T15:35:33Z,0,"STILL WATCHING FIRST VIDEO but came here to say ""FIRST"".........",True
