author,updated_at,like_count,text,public
@TXfoxie,2020-06-10T22:14:04Z,0,"I took a resolution of full scale, and OMG it took 5 minutes to load the map.",True
@sayedrizbanhussain109,2020-04-09T21:37:57Z,0,"I am getting this error when i try to draw, m.etopo() and m.bluemarble(). I am using python 3.8.2 32 bit Traceback (most recent call last):   File ""E:/Machine Learning/Matplotlib Tutorial/basemapIntro.py"", line 52, in <module>     m.bluemarble()   File ""C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mpl_toolkits\basemap\__init__.py"", line 3961, in bluemarble     return self.warpimage(image='bluemarble',scale=scale,**kwargs)   File ""C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mpl_toolkits\basemap\__init__.py"", line 4122, in warpimage     self._bm_rgba_warped = np.ones((ny,nx,4),np.float64)   File ""C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numpy\core\numeric.py"", line 207, in ones     a = empty(shape, dtype, order) MemoryError: Unable to allocate 653. MiB for an array with shape (3960, 5401, 4) and data type float64",True
@chrislam1341,2019-08-31T18:48:56Z,0,how can I know exactly a location coordination? where could i have that infomation?,True
@rdmedic71,2019-05-02T14:28:52Z,1,"If you get an error with the m.drawcounties due to encode issues..... Try this.... it worked for me. I found this solution on stackoverflow:    I have the same problem. I've solved it. I replace all ""utf-8"" with ""latin-1"" in shapefile.py, which located in ~/Library/Python/3.7/lib/python/site-packages/shapefile.py     Before I could save the changes, I had to get permission to edit the folders.  I followed this youtube tutorial and that fixed that problem.  https://www.youtube.com/watch?v=3LnnvbpO9NI",True
@rdmedic71,2019-05-02T12:06:16Z,1,"Sooooo, I'm loving your classes.  However,  I have to point out that latitude is the horizontal lines on the map, and Longitude is the vertical lines on a map. https://journeynorth.org/tm/LongitudeIntro.html I'm curious if this impacts the code example you're giving.  But I digress.  on with the class.  Thanks,",True
@ezio8317,2019-03-07T20:55:59Z,1,"line ""m.drawcounties(color='darkred')"" show an error of:  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 2: invalid continuation byte the modify that is hint isn't correct! how i can do?",True
@ianbrink8359,2019-02-02T11:44:04Z,2,You are a legend... and not a map legend... a gladiator legend!!! Useful tuts!,True
@elmirach4706,2018-11-04T23:14:35Z,0,"Everything works fine till I try to  ""  m.plot( xpt, ypt, 'c*', markersize=15)"" plot the location of NY or LA on a map. Then I get an error ""return plotfunc(self,x,y,*args,**kwargs)   File ""C:\...\Python\Python36\lib\site-packages\mpl_toolkits\basemap\__init__.py"", line 3285, in plot     self._restore_hold(ax)   File ""C:\...\Python36\lib\site-packages\mpl_toolkits\basemap\__init__.py"", line 3229, in _restore_hold     ax._hold = self._tmp_hold AttributeError: can't set attribute""  Please somebody help me to solve the problem",True
@mannana.z.9904,2018-09-28T09:10:56Z,0,"Hello, I am using basemap to generate a plot for representing CO2 but i need to produce filled contour map of the different concentration at different locations (Lat and Long). Now for generating those maps i need to interpolate the points and this method can be done by nearest neighbour method (interpolation of co2 points). Unfortunately, python is asking me to install (natgrid) library which is so hectic to install. Can you please give me some suggestion on installing natgrid library i have already tried all options.",True
@mozarter86,2018-08-08T22:49:34Z,0,"line ""m.drawcounties(color='darkred')"" show an error of:  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 2: invalid continuation byte  guess some country does not encode as utf-8?",True
@aniketmitra9271,2018-06-26T10:34:58Z,0,How to get all the country names inside a continent?,True
@sreenjaysen927,2018-06-10T15:58:23Z,2,latitudes are the horizontal lines while longitudes are the vertical lines,True
@ravikumargogineni1969,2017-10-14T03:38:26Z,0,"m =Basemap(projection='mill',    llcrnrlat=8,     llcrnrlon=67,     urcrnrlat=37,    urcrnrlon=97,   resolution='h') m.drawcoastlines() m.drawcountries(linewidth=1) m.drawstates(color='k') plt.title('Basic map') plt.show()  But the states are not showing. It shows plain map. How can I show states also for india map?",True
@thisisprabin,2017-04-14T10:26:30Z,0,"Hi i am getting some errors  Traceback (most recent call last):   File ""p5.py"", line 14, in <module>     m.etopo()   File ""/usr/lib/python2.7/dist-packages/mpl_toolkits/basemap/__init__.py"", line 4017, in etopo     return self.warpimage(image='etopo',scale=scale,**kwargs)   File ""/usr/lib/python2.7/dist-packages/mpl_toolkits/basemap/__init__.py"", line 4117, in warpimage     np.concatenate((self._bm_lons,self._bm_lons+360),1) IndexError: axis 1 out of bounds [0, 1)",True
@thehornandhoof,2016-11-11T09:10:39Z,1,Latitude are parallel to equator (horizontal) and Longitude go vertical (up to down).  https://en.wikipedia.org/wiki/Geographic_coordinate_system#Geographic_latitude_and_longitude  Anyways tons of thanks for great tutorials.,True
@daniz001,2016-10-06T22:21:26Z,0,"Hi, Thank  you very much for the tutorial. This is AWESOME!!  I am getting this error when I add m.etopo() line. Do you have any idea why that function is not working? I am using python 3.5     File ""C:\Anaconda3\lib\site-packages\mpl_toolkits\basemap\__init__.py"", line 4167, in warpimage     np.concatenate((self._bm_lons,self._bm_lons+360),1)  IndexError: axis 1 out of bounds [0, 1)",True
@RealMcDudu,2016-06-25T10:54:58Z,0,Is there anyway to increase resolution on the bluemarble thing? (or get something else with higher resolution?),True
@tmattoneill,2016-04-12T17:23:29Z,0,"After adding the m.counties [with or without a colour] I get a series of errors: Traceback (most recent call last):   File ""/Users/moneill/basemap_02.py"", line 13, in <module>     m.drawcounties(color='darkred')   File ""/usr/local/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py"", line 1980, in drawcounties     default_encoding='latin-1',drawbounds=drawbounds)   File ""/usr/local/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py"", line 2146, in readshapefile     for shprec in shf.shapeRecords():   File ""/usr/local/lib/python3.5/site-packages/mpl_toolkits/basemap/shapefile.py"", line 543, in shapeRecords     for rec in zip(self.shapes(), self.records())]   File ""/usr/local/lib/python3.5/site-packages/mpl_toolkits/basemap/shapefile.py"", line 515, in records     r = self.__record()   File ""/usr/local/lib/python3.5/site-packages/mpl_toolkits/basemap/shapefile.py"", line 491, in __record     value = u(value)   File ""/usr/local/lib/python3.5/site-packages/mpl_toolkits/basemap/shapefile.py"", line 58, in u     return v.decode('utf-8') UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 2: invalid continuation byte  Anyone else get this?",True
@ariramkilowan8051,2016-04-12T06:26:29Z,2,"You kind sir, take my like! Huzzah",True
@shantanurahman5084,2015-12-30T14:12:11Z,0,"A little trouble here..  after adding m.etopo() this happens  Traceback (most recent call last):   File ""E:\Python\Matplotlib\Basemap\test1.py"", line 14, in <module>     m.etopo()   File ""C:\Python34\lib\site-packages\mpl_toolkits\basemap\__init__.py"", line 4061, in etopo     return self.warpimage(image='etopo',scale=scale,**kwargs)   File ""C:\Python34\lib\site-packages\mpl_toolkits\basemap\__init__.py"", line 4167, in warpimage     np.concatenate((self._bm_lons,self._bm_lons+360),1) IndexError: axis 1 out of bounds [0, 1)",True
@Ralph_-_,2015-08-11T08:03:26Z,5,"Thanks for the great tutorials! And a tip for other watchers, install Pillow for the last function (bluemarble)",True
