author,updated_at,like_count,text,public
@joxa6119,2022-04-29T02:15:42Z,0,"Traceback (most recent call last): line 25, in classify      v = c.classify(features) AttributeError: '_io.BufferedReader' object has no attribute 'classify'  I got this error :(",True
@yogeshwarshendye4857,2022-04-10T11:27:43Z,0,Somehow in linux the positive.txt and negative.txt are not being able to be read in UTF-8 encoding..so I tried with latin-1 and man it gives so many errors!!,True
@pauladediosoliver7143,2022-02-05T17:44:47Z,0,"For any one who needs, I got an error when running sentiment_mod and it was because the feature set was not ""pickled"". After find_features function goes this code and it worked for me !   featuresets = [(find_features(rev), category) for (rev, category) in documents]  random.shuffle(featuresets) print(len(featuresets))  featuresets_txt =  open(""pickled_algos/featuresets.pickle"", ""wb"") #opening a featursets picle  testing_set = featuresets[10000:] training_set = featuresets[:10000] pickle.dump(featuresets,featuresets_txt) #dumpining into the pickle featuresets_txt.close() #closing the pickle",True
@edwardj.warden5072,2021-12-01T12:05:46Z,0,"Hi I been following your video, I love your tutorial and I have learned lot of thing out of your tutorial. Thank you for your work. As I been following this tutorial I found a problem and I tried many times to correct my issue but couldn't, may be you can help me on this,  <ipython-input-18-d231ff96dcee> in <module> ----> 1 import sentiment_mod as s       2        3 print(s.sentiment(""This movie was awesome! The acting was great, plot was wonderful, and there were pythons...so yea!""))       4 print(s.sentiment(""This movie was utter junk. There were absolutely 0 pythons. I don't see what the point was at all. Horrible movie, 0/10""))  ~\Natural_Language_Processing (NLP)\sentiment_mod.py in <module>     136   {     137    ""cell_type"": ""code"", --> 138    ""execution_count"": null,     139    ""id"": ""9aa8dce5"",     140    ""metadata"": {},  NameError: name 'null' is not defined",True
@yookoT,2021-10-08T11:25:44Z,0,"Thanks for this very good course, I followed the whole course to make this program and I made it, which is very fulfilling.",True
@Diego01201,2021-07-01T16:33:12Z,1,"Thanks for the tutorial. But really, you need some software engineering classes if you keep this code like this nowadays. It is very messy.",True
@architraghuvanshi8892,2020-07-29T11:50:17Z,0,.,True
@marufakamallabonno146,2020-04-20T07:41:04Z,0,"raise ValueError(""Sample sequence X is empty."")  ValueError: Sample sequence X is empty.   does anybody get this error ?",True
@khalilsaqib8176,2020-04-02T13:35:53Z,0,its gives negative every time,True
@digvijayyadav3633,2020-03-28T04:34:37Z,0,which video is about pickling?,True
@LSD1317,2020-01-16T21:42:42Z,0,"Your videos are great. Keep it up, man! By the way, do u have a github account. If yes then link it please",True
@maxbranco7321,2020-01-06T02:11:49Z,0,"# Only taught of doing this after manually doing all the pickling:    def pickle_stuff(stuff):     from pickle import dump     open_file = open(f""pickled_stuff/{stuff}.pickle"", ""wb"")     dump(stuff, open_file)     open_file.close()   stuff_to_pickle = {      documents,     feature_sets,     word_features,      original_classifier,     NuSVC_classifier,     LinearSVC_classifier,     SVC_classifier,     SGDClassifier_classifier,     LogisticRegression_classifier,     BernoulliNB_classifier,     MNB_classifier    }  for s in stuff_to_pickle:      pickle_stuff(s)",True
@vlinkin22,2019-10-17T19:45:55Z,0,"""I opened the window"" it's negative haha",True
@krupagajjar5410,2019-09-04T18:53:29Z,0,"from where can i get this code, sir :)",True
@elvisidrizi2847,2019-08-11T15:23:24Z,0,"Hello @sentdex, i enjoy your videos. I have a question regarding the s.sentiment.  Is it possible that s. sentiment reviews a whole document not just a short text for me to write. Thanks in advance.",True
@varghesebernard9974,2019-08-11T10:47:08Z,0,I am always getting classified as neg !,True
@dipendrakarki662,2019-08-02T17:08:22Z,0,"Could you please elaborate why we can't pickle the ""voted classifier""?",True
@ravisamal3533,2019-07-12T07:21:39Z,1,how can i extract emotions from a text .a video would help,True
@amithedaoo5619,2019-06-30T08:18:15Z,0,"Getting an error Traceback (most recent call last):   File ""/home/Natural Language Processing/sentiment_mod.py"", line 64, in <module>     random.shuffle(featuresets)   File ""/usr/lib/python3.6/random.py"", line 274, in shuffle     for i in reversed(range(1, len(x))): TypeError: object of type 'NaiveBayesClassifier' has no len()",True
@jav4725,2019-06-29T12:04:11Z,0,"help me with this error    File ""/Users/admin/anaconda3/lib/python3.7/site-packages/nltk/classify/scikitlearn.py"", line 70, in __init__     self._encoder = LabelEncoder()  NameError: name 'LabelEncoder' is not defined",True
@tapaskar1,2019-05-27T22:40:46Z,0,"Hey everyone. I have a question regarding saving the classifiers. When I try to run my program I get the following error:     Traceback (most recent call last):   File ""C:/Users/HP/PycharmProjects/NLTK Files in Pycharm/Creating a Module for Sentiment Analysis.py"", line 109, in <module>     MNB_classifier.train(training_set)   File ""C:\Users\HP\venv\NLTK Files in Pycharm\lib\site-packages\nltk\classify\scikitlearn.py"", line 117, in train     X = self._vectorizer.fit_transform(X)   File ""C:\Users\HP\venv\NLTK Files in Pycharm\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 229, in fit_transform     return self._transform(X, fitting=True)   File ""C:\Users\HP\venv\NLTK Files in Pycharm\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 170, in _transform     indices.append(vocab[f]) MemoryError     Could anyone please help me out ? I looked it up and it said that it was a memory problem. What could I do to fix it ? Thank you in advance.",True
@GelsYT,2019-05-06T07:26:49Z,0,link for the source code please :D thank youuuuuu <3,True
@navneetkaur5820,2018-10-14T06:33:56Z,0,"Can anyone help me with this error :  Traceback (most recent call last):   File ""C:/Users/a to z/Documents/Python/sentiment_mod.py"", line 55, in <module>     featuresets = pickle.load(featuresets_f)   File ""C:\Python27\lib\pickle.py"", line 1384, in load     return Unpickler(file).load()   File ""C:\Python27\lib\pickle.py"", line 864, in load     dispatch[key](self)   File ""C:\Python27\lib\pickle.py"", line 892, in load_proto     raise ValueError, ""unsupported pickle protocol: %d"" % proto ValueError: unsupported pickle protocol: 3",True
@KulvinderSingh-pm7cr,2018-10-01T19:33:58Z,0,You are wonderful brother !!,True
@karmanchawla1227,2018-09-23T10:31:23Z,0,"I have copied and pasted the exact code from pythonprogramming.net so the line refrence can be taken from there and I'm getting this error. Traceback (most recent call last):   File ""C:/Users/Karman Chawla/Desktop/Project/Save_Classifier.py"", line 110, in <module>     MNB_classifier.train(training_set)   File ""C:\Users\Karman Chawla\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nltk\classify\scikitlearn.py"", line 117, in train     X = self._vectorizer.fit_transform(X)   File ""C:\Users\Karman Chawla\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 230, in fit_transform     return self._transform(X, fitting=True)   File ""C:\Users\Karman Chawla\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 171, in _transform     indices.append(vocab[f]) MemoryError",True
@amanupadhyay3527,2018-08-14T07:37:15Z,0,"FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.   ""and default tol will be 1e-3."" % type(self), FutureWarning)    I am encountered with this error how to solve this.",True
@sanasayyed1830,2018-07-14T17:29:19Z,0,please give me the code of it,True
@dingxinwu6849,2018-07-11T00:49:54Z,1,"Question: in sentiment_mod.py, why do we need to load documents.pickle and featureset.pickle since we have already trained our classifiers..i commented out those code and it works well too",True
@sujanmaharjan224,2018-07-01T10:56:56Z,0,"NameError: return codecs.charmap_decode(input,self.errors,decoding_table)[0] UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1769: character maps to <undefined> Somebody help me with this.",True
@user-zi3qq9ef1g,2018-05-23T18:41:12Z,0,Where should I save short_reviews?,True
@McDiego015,2018-04-20T15:33:37Z,0,"jaja I think I have done something wrong in here LOL:  print(s.sentiment(""This movie was awesome! The acting was great, plot was wonderful, and there were pythons...so yea!"")) ('neg', 0.8571428571428571)",True
@ashwindhakal110,2018-03-04T12:47:04Z,2,"I got to see most of the friends are having trouble with featuresets.pickle  So, I have shared this file for your comfort. Have a look here at my github: https://github.com/Ashwin-Dhakal/real-time-tweet-sentiment-analysis .  Make sure you look at the read-me section and put featuresets.pickle file inside pickled_algos after downloading it. Thank me later :)",True
@clientservices8846,2018-02-16T18:45:26Z,0,"Two and a half years later, still a great tutorial. Thanks.  Just FYI... fully pickling on a 2017 iMac went from 4.4 minutes to 4.5 seconds.",True
@katiewilliams7550,2018-02-01T15:00:41Z,0,is there any way we can make a website interface so the user can input their own keyword and press a button to generate graph?,True
@hosseinheydari596,2018-01-31T09:33:59Z,0,"hi @sentdex ive been following your tutorial and ive been stuck on this for a few days when i run mycode i get the following error :   Traceback (most recent call last):   File ""test.py"", line 1, in <module>     import sentiment_mod as s   File ""/Users/wasp/Desktop/PythonNLTK/sentiment_mod.py"", line 65, in <module>     random.shuffle(featuresets)   File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py"", line 288, in shuffle     for i in reversed(xrange(1, len(x))): TypeError: object of type 'SklearnClassifier' has no len()   i would appreciate it if you can give me some advice so this problem can get pythoned XD",True
@karamalassaf9901,2018-01-24T13:37:25Z,0,"Would anyone happen to know the solution to this error?    Traceback (most recent call last):   File ""/Users/omaral-assaf/Desktop/Python/sentiment_mod.py"", line 40, in <module>     short_pos = open(""positive.txt"",""r"").read().encode('utf-8').strip()   File ""/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py"", line 26, in decode     return codecs.ascii_decode(input, self.errors)[0] UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 4645: ordinal not in range(128)",True
@karamalassaf9901,2018-01-24T11:09:00Z,0,the files that are used (short_review/positive.txt and short_review/negative.txt) where do we get those? do we create them? or will python create them?,True
@maranb8,2018-01-05T09:15:38Z,0,I need featuresets.pickle if anyone is having please do mail me on maran.b8@gmail.com please,True
@baskarsurya5992,2018-01-05T08:59:31Z,1,can anyone mail me the featuresets.pickle . I could not find it anywhere please mail me to maran.b8@gmail.com. This is my project so please do kind.,True
@PMayhew,2017-12-20T11:15:37Z,0,"When running this code I have a python message saying memory error. I am using the 32-bit version of Python, and see you are using the 64-bit version. Is the 64-bit version required for the tutorial?",True
@lisashil2901,2017-11-25T07:25:04Z,0,I got error no2 - no such file or directory: 'pickled_algos/documents I need help.,True
@gunjanaggarwal1301,2017-11-03T09:49:41Z,0,my confidence is coming out to be 0 for both reviews and category 'pos',True
@gunjanaggarwal1301,2017-11-02T15:08:21Z,0,"when i import sentiment_mod in another file, whole sentiment_mod is running, instead of just the function ""sentiment"". Moreover, it is saying that ""find_features"" function is not defined. however i have defined it.",True
@wisdom_world_official,2017-10-18T14:23:15Z,1,"I am using python 3.6.3 . All the packages have been successfully imported. I am using 32 bit version. I am getting this memory error:      Traceback (most recent call last):       File ""C:/Users/Lokesh/PycharmProjects/NLP/Training.py"", line 103, in <module>              print(""MNB_classifier accuracy percent:"", (nltk.classify.accuracy(MNB_classifier, testing_set)) * 100)            File ""C:\Users\Lokesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nltk\classify\util.py"", line 87, in accuracy         results = classifier.classify_many([fs for (fs, l) in gold])            File ""C:\Users\Lokesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nltk\classify\scikitlearn.py"", line 85, in classify_many         X = self._vectorizer.transform(featuresets)            File ""C:\Users\Lokesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 291, in transform         return self._transform(X, fitting=False)          File ""C:\Users\Lokesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 171, in _transform         indices.append(vocab[f])     MemoryError",True
@siddharthuniyal1615,2017-09-11T13:39:22Z,2,"Hi sentdex  I am getting the following error :-  Traceback (most recent call last):   File ""D:\Users\siddharth.u\Documents\Natural Language Processing\Creating a module for Sentiment Analysis with NLTK\Creating a module for Sentiment Analysis with NLTK.py"", line 103, in <module>     MNB_classifier.train(training_set)   File ""D:\Users\siddharth.u\AppData\Local\Continuum\Anaconda3\lib\site-packages\nltk\classify\scikitlearn.py"", line 117, in train     X = self._vectorizer.fit_transform(X)   File ""D:\Users\siddharth.u\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 230, in fit_transform     return self._transform(X, fitting=True)   File ""D:\Users\siddharth.u\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 172, in _transform     values.append(dtype(v)) MemoryError  Please help!",True
@abhishekpatel7812,2017-08-27T19:53:22Z,2,"for people getting error for featuresets.pickle is missing ! put this code  ----------------------------------------------------------------------------- fset = open(""pickled_algos/featuresets.pickle"", ""wb"") pickle.dump(featuresets,fset) fset.close() ----------------------------------------------------------------------------  below this   random.shuffle(featuresets) print(len(featuresets))",True
@ruixuewang9532,2017-08-12T16:09:53Z,0,"IOError: No such file or directory:""pickled_algos/documents.pickle"" Please help!",True
@aldosanjoto8296,2017-07-31T10:09:35Z,0,why is the confidence percentage keep outputting either 0% or 100% ?,True
@aldosanjoto8296,2017-07-31T09:16:38Z,0,why does SGDClassifier creates an error for voted_classifer? +sentdex (I noticed you removed it in the code),True
@tnshk21,2017-07-22T10:24:14Z,0,"featureset pickling - i am using this , but it does not writes anything to my file ?? help save_featuresets = open(""featuresets.pickle"",""wb"") pickle.dump(featuresets,save_featuresets) save_featuresets.close()",True
@demodummy1930,2017-07-22T07:00:09Z,0,how can we identify the top attributed based on sentiment for which customers are talking about?  Kindly reply asap.,True
@MuhammadArshad,2017-07-18T20:19:55Z,0,I wish you had use the protocol less than 2 when you were dumping the data into pickles :( Can't use them in Python2 now. Any workaround?,True
@vinayakbansal599,2017-06-22T05:50:41Z,0,I pickled them in 6 minutes :v :D,True
@16avnisharma,2017-06-08T06:50:23Z,2,"I am getting  10664 ('neg', 0) ('neg', 1) ('neg', 0) for the inputs  print s.sentiment(""ok"") print s.sentiment(""bad"") print s.sentiment(""good"")  why am I getting all 'neg'. Please help :(",True
@ulysses3183,2017-05-25T17:13:31Z,0,How do you import this created module if you made it in ipython notebook?,True
@kylez6424,2017-05-17T16:16:53Z,1,"Hey dude, thank you again for all the great videos!  Hey I forgot which video but I want to comment that Gaussian naive Bayes wouldn't work for our case. Becuase the assumption is that continuous values associated with each class are distributed according to a Gaussian distribution.   Whereas for our example, each word(feature) is binary, and there is no normal distribution",True
,2017-04-07T23:46:57Z,1,"So strange... ""I want to be mom"" it's negative... haha",True
@AshishGupta-xm7dh,2017-04-02T14:38:18Z,0,"File ""C:\Python27\tryingagain4.py"", line 46, in <module>     words = word_tokenize(p).............. ...................................................... .........   File ""C:\Python27\lib\site-packages\nltk\tokenize\punkt.py"", line 542, in _tokenize_words     for line in plaintext.split('\n'): UnicodeDecodeError: 'ascii' codec can't decode byte 0x96 in position 2: ordinal not in range(128)  Also this error pops up",True
@AshishGupta-xm7dh,2017-04-02T12:50:20Z,0,"Help Help!!! @Sentdex I always get ""neg"" when trying to analyse a simple text. here is my code. I am only using naive bayes algorithm   import nltk import random from nltk.corpus import movie_reviews  documents = [(list(movie_reviews.words(fileid)),category)              for category in movie_reviews.categories()              for fileid in movie_reviews.fileids(category)]  random.shuffle(documents) all_words = []  for w in movie_reviews.words():     all_words.append(w.lower())  all_words = nltk.FreqDist(all_words) word_features = list(all_words.keys())[:3000]  def find_features(document):     words = set(document)     features = {}     for w in word_features:         features[w] = (w in words)     return features   featuresets = [(find_features(rev), category) for (rev, category) in documents] train_set, test_set = featuresets[1000:], featuresets[:1000] classifier = nltk.NaiveBayesClassifier.train(train_set)  print(nltk.classify.accuracy(classifier, test_set)) classifier.show_most_informative_features(15)  print classifier.classify(find_features(""golden movie with catchy acting""))   What's Wrong can you help me  :(",True
@VishalKumar-eb7sp,2017-03-25T23:16:59Z,0,@sentdex How to remove this error....   testing_set = featuresets[10000:]   TypeError: unhashable type: 'slice',True
@RahulRaj-tg2kr,2017-03-09T21:00:30Z,0,"Traceback (most recent call last):   File ""C:/Users/rahul/AppData/Local/Programs/Python/Python35/sentiment_mod.py"", line 8, in <module>     from sklearn.naive_bayes import MultinomialNB, BernoulliNB   File ""C:\Users\rahul\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\__init__.py"", line 57, in <module>     from .base import clone   File ""C:\Users\rahul\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\base.py"", line 10, in <module>     from scipy import sparse ImportError: No module named 'scipy'   please help in solving this error immediatelt Sir Its quite urgent where and how to install module scipy to avoid above error",True
@abhinavtyagi1804,2017-03-09T07:31:23Z,0,I got exact same accuracy for Original and Bernoulli classifiers every time...  Original_classifier Accuracy -> 73.94578313253012 MNB_classifier Accuracy -> 72.59036144578313 BernoulliNB_classifier Accuracy -> 73.94578313253012 LogisticRegression_classifier Accuracy -> 72.7409638554217 SGDClassifier_classifier Accuracy -> 72.13855421686746 LinearSVC_classifier Accuracy -> 70.63253012048193,True
@saileephadtare8043,2017-02-28T19:00:27Z,0,"i am getting this warning,how to solve it?   UserWarning: Trying to unpickle estimator LabelEncoder from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.",True
@agraneebanerjee305,2017-01-31T17:44:41Z,0,please upload featuresets.pickle in github,True
@AbhijeetChavan2512,2017-01-24T02:30:00Z,0,"+sentdex everytime when i am trying to train classifiers it shows the MemoryError even when i downsized the training data to  500  Traceback (most recent call last):   File ""C:\Python\SentReviews.py"", line 107, in <module>     print(""MNB_classifier accuracy percent:"", (nltk.classify.accuracy(MNB_classifier, testing_set))*100)   File ""C:\Python\lib\site-packages\nltk\classify\util.py"", line 87, in accuracy     results = classifier.classify_many([fs for (fs, l) in gold])   File ""C:\Python\lib\site-packages\nltk\classify\scikitlearn.py"", line 83, in classify_many     X = self._vectorizer.transform(featuresets)   File ""C:\Python\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 293, in transform     return self._transform(X, fitting=False)   File ""C:\Python\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 173, in _transform     values.append(dtype(v)) MemoryError",True
@narayannandeda3987,2017-01-07T18:08:05Z,0,"Hi, these videos are awesome.. Thanks Sentdex...",True
@danielsanchez7393,2016-11-08T00:21:41Z,0,"Hi, this videos are asome, so i have a question how can i do this but in spanish ? a sentiment  but in spanish thaks..",True
@anonymosthucker5120,2016-10-30T06:28:15Z,0,"I always having a pos result, why is that happening to me",True
@rafaelvalerofernande,2016-10-21T15:48:17Z,0,"Great staff!! I will sugest to change ""wb"" for ""wb+"" particularly for the first time is run",True
@kirancsk,2016-09-22T17:12:33Z,0,"Thanks for the great tutorials . They are such a great help to get started on NLP.   Can you suggest any known techniques for doing sentiment analysis for each entity in a text piece? I.e, when more than one entity is being talked about in the text, I am looking for ways to analyze sentiment specific to each entity.  Thank you.",True
@Ravi86055,2016-09-11T08:01:00Z,0,"Hi Guys, I'm getting the below issue when i run the code. Could any one one of you suggest me to proceed to further.  ""ValueError: unsupported pickle protocol: 3""  I'm Python using pythong 2.7 version. i tried cpickler instead of pickler, but it didn't work for me. Any help would be greatly appreciable....",True
@RaoufGnda,2016-08-25T17:36:49Z,3,featuresets.pickle is missing !,True
@RaoufGnda,2016-08-24T23:39:24Z,1,I need help we this error guys 'ascii' codec can't decode byte 0x96 in position 2: ordinal not in range(128),True
@blairyoung6088,2016-08-06T15:53:12Z,0,"Hey, I'm having trouble pickling the my dataset. Its about the same size as yours but when i pickle the featureset it takes forever when I load it  back in. I had a look at the file size and its 130mb. is there something I'm over looking? thanks",True
@willhatch7721,2016-08-04T00:31:34Z,0,"You couldn't pickle the voting classifier because pickle is saving an instance of a class, and you only use this class as a method wrapper and aren't working with a persistent instantiation of it. I think... I'm new to Py",True
@thewackydose,2016-07-30T03:09:28Z,0,"Everytime i run this program. I get the following error:  Traceback (most recent call last):   File ""<tmp 1>"", line 72, in <module>     SGDC_classifier.train(training_set)   File ""c:\users\rohit\miniconda3\lib\site-packages\nltk\classify\scikitlearn.py"", line 115, in train     X = self._vectorizer.fit_transform(X)   File ""c:\users\rohit\miniconda3\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 226, in fit_transform     return self._transform(X, fitting=True)   File ""c:\users\rohit\miniconda3\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 168, in _transform     values.append(dtype(v)) MemoryError",True
@sandeeptadepalli5963,2016-07-07T09:24:30Z,0,+sentdex. I want to improve my classifier every time. Every time the algo gave a wrong prediction I want to include that dynamically into my training set so that my classifier keeps getting better.  But the problem is I cant pickle it then is there any other way!? help me over this  I Hope this is  a valid question,True
@rodrigoribeiro2468,2016-05-13T20:12:33Z,0,"Hi Harrison,   Could you explain this part of the code?    featuresets = [(find_features(rev), category) for (rev, category) in documents]   Also if at  this moment are you using movie_reviews or your files ""short_reviews"" ? I'm really confused with that.",True
@pranavgoel8205,2016-05-11T18:03:14Z,0,"sentdex ,  I must say that your tutorial series is wonderful, and I am enjoying myself thoroughly. So a big Thank You!I would be grateful if you could help me out with this error though (or if anyone can) Traceback (most recent call last):   File ""D:/nltk_python/example_to_use_sentiment_mod.py"", line 3, in <module>     print(s.sentiment(""This movie was awesome! The acting was great, plot was wonderful, and there were pythons...so yea!""))   File ""D:\nltk_python\sentiment_mod.py"", line 118, in sentiment     return voted_classifier.classify(feats),voted_classifier.confidence(feats)   File ""D:\nltk_python\sentiment_mod.py"", line 24, in classify     v = c.classify(features)   File ""C:\Users\HP\Anaconda3\lib\site-packages\nltk\classify\api.py"", line 54, in classify     return self.classify_many([featureset])[0]   File ""C:\Users\HP\Anaconda3\lib\site-packages\nltk\classify\scikitlearn.py"", line 85, in classify_many     return [classes[i] for i in self._clf.predict(X)]   File ""C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\base.py"", line 273, in predict     return self.classes_[indices] AttributeError: 'LinearSVC' object has no attribute 'classes_'",True
@Ghumakkad-Bitiya,2016-04-30T02:48:16Z,0,Where is the source code? could you please give link of source code?,True
@ADITYAAISHWARY,2016-04-09T11:33:37Z,0,"+sentdex  I dont understand when and where ""featuresets.pickle"" got created. Searched a lot could not find. when i run sentiment_mod.py I get the following error:  Traceback (most recent call last):   File ""/Users/adityaaishwary/Documents/sentiment_mod.py"", line 59, in <module>     featuresets_f = open(""pickled_algos/featuresets.pickle"", ""rb"") FileNotFoundError: [Errno 2] No such file or directory: 'pickled_algos/featuresets.pickle'   please share the file feature sets.pickle or help me out of it.",True
@anjalirathore5994,2016-04-09T07:35:32Z,0,"Traceback (most recent call last):   File ""C:\Users\hp pc\AppData\Local\Programs\Python\Python35-32\nj.py"", line 6, in <module>     from sklearn.naive_bayes import MultinomialNB, BernoulliNB   File ""C:\Users\hp pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sklearn\__init__.py"", line 57, in <module>     from .base import clone   File ""C:\Users\hp pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sklearn\base.py"", line 9, in <module>     from scipy import sparse   File ""C:\Users\hp pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\scipy\sparse\__init__.py"", line 214, in <module>     from .csr import *   File ""C:\Users\hp pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\scipy\sparse\csr.py"", line 13, in <module>     from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \ ImportError: DLL load failed: The specified module could not be found. THIS ERROR IS COMING OUT.. PLZ SUGGEST SOME SOLUTION +sentdex",True
@purnimabaskar5287,2016-03-31T11:25:17Z,1,'LinearSVC' object has no attribute 'classes_',True
@purnimabaskar5287,2016-03-31T09:11:43Z,1,"Traceback (most recent call last):   File ""C:/Python34/sentiment_mod.py"", line 110, in <module>     print(sentiment(""This is bad""))   File ""C:/Python34/sentiment_mod.py"", line 103, in sentiment     return voted_classifier.classify(feats),voted_classifier.confidence(feats)   File ""C:/Python34/sentiment_mod.py"", line 24, in classify     v = c.classify(features)   File ""C:\Python34\lib\site-packages\nltk\classify\api.py"", line 54, in classify     return self.classify_many([featureset])[0]   File ""C:\Python34\lib\site-packages\nltk\classify\scikitlearn.py"", line 85, in classify_many     return [classes[i] for i in self._clf.predict(X)]   File ""C:\Python34\lib\site-packages\sklearn\linear_model\base.py"", line 273, in predict     return self.classes_[indices] AttributeError: 'LinearSVC' object has no attribute 'classes_'    im getting this error when running sentiment_mod..pls do help",True
@purnimabaskar5287,2016-03-31T08:53:53Z,1,featuresets = pickle.load(featuresets_f) EOFError: Ran out of input  pls..do rectify my error,True
@SujitJadhav08,2016-03-27T05:39:17Z,0,"In sentiment_mod.py file, you have loaded ""featuresets.pickle"" file. I an unable to find as well as create. Please help me",True
@SomethingStrange910,2016-03-27T02:57:49Z,2,"If anyone is experiencing an error like I did: File ""C:\Anaconda3\lib\site-packages\nltk\tag\__init__.py"", line 110, in pos_tag     tagger = PerceptronTagger(), try this: pip install nltk==3.1",True
@dr.azizyarahmadi5143,2016-03-09T14:23:19Z,0,Thanks for the wonderful explanation.But how long does it take to do the first part?mine actually is working for hours and still going on! thanks,True
@shivGGG,2016-03-08T08:36:11Z,0,Error :   /usr/lib/python2.7/site-packages/numpy-1.11.0rc1-py2.7-linux-x86_64.egg/numpy/cor                                                                                       e/fromnumeric.py:2652: VisibleDeprecationWarning: `rank` is deprecated; use the `                                                                                       ndim` attribute or function instead. To find the rank of a matrix see `numpy.lina                                                                                       lg.matrix_rank`.   VisibleDeprecationWarning)  On linux,True
@jibintk9872,2016-02-29T15:52:10Z,0,where to put sentiment_mod.py..I'm doing it in ubuntu,True
@jibintk9872,2016-02-29T14:14:47Z,0,"sir can u please post the full source code,including pickled algos",True
@danielravina130,2016-02-14T20:57:28Z,0,Thank you so much for the videos!,True
@harnanimatzin2762,2016-01-28T07:42:07Z,0,I have a question. Where I can get the 'short_reviews/positive.txt,True
@harnanimatzin2762,2016-01-28T07:33:35Z,0,"Hi. I tried to run this code but I didn't used the pickle function. Unluckily, it is not working for me. When I run the code, i get this error:  Traceback (most recent call last):   File ""<string>"", line 254, in run_nodebug   File ""E:\Development\Tutorial\sentiment_mod.py"", line 96, in <module>     print (""MNB_classifier accuracy percent:"", (nltk.classify.accuracy(MNB_classifier, testing_set))*100)   File ""C:\Python27\lib\site-packages\nltk\classify\util.py"", line 87, in accuracy     results = classifier.classify_many([fs for (fs,l) in gold])   File ""C:\Python27\lib\site-packages\nltk\classify\scikitlearn.py"", line 84, in classify_many     X = self._vectorizer.transform(featuresets)   File ""C:\Python27\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 286, in transform     return self._transform(X, fitting=False)   File ""C:\Python27\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py"", line 177, in _transform     raise ValueError(""Sample sequence X is empty."") ValueError: Sample sequence X is empty.  Anybody can help me solve this problem? Thanks",True
@lenofire586543,2015-12-30T05:28:01Z,3,Where were the featuresets.pickle? I cannot find featuresets.pickle on github. can you upload it in github?,True
@aliflodi9857,2015-12-07T21:21:55Z,0,my compiler is compiling the first file which is not sentiment_mod py for atleast half an hour. is that a problem?,True
@Weakbody2,2015-11-26T08:31:12Z,0,How do I know when idle is done running? I have left it for hours.,True
@vmueller,2015-11-12T18:58:10Z,0,"Hi sentdex, could you please provide your pickle files? I am getting always an Memory Error and can not compile it. It would be really helpful. Thank you!",True
@niharns1,2015-10-14T09:25:50Z,1,"@sentdex  why cant we just load the pickled algos. i mean for ex:  if we just load this two things and not featureset will it work. coz while pickling we are already saving our originalnaivebayes5k classifier.  word_features5k_f = open(""pickled_algos/word_features5k.pickle"", ""rb"") word_features = pickle.load(word_features5k_f) word_features5k_f.close()  open_file = open(""pickled_algos/originalnaivebayes5k.pickle"", ""rb"") classifier = pickle.load(open_file) open_file.close()  the reason is the feature set file is very big in size and it takes lot of time to load that featureset.",True
@niharns1,2015-10-12T09:19:40Z,0,"+sentdex hi, I have 2 doubts.  1) We are not saving featuresets, yet we are loading it in final module. how?  2) I am getting an error as:      pickle.dump(documents, save_classifier) NameError: name 'save_classifier' is not defined  i think instead of ""save_classifier"" it should be ""save_documents"". please correct me if i am wrong.",True
@gaslight0513,2015-09-26T21:08:27Z,0,Edit: I found that trying to create a pickle for featuresets (I think the mod code you posted loads one in) results in a 500 MB pickle. Remove the saving of the pickle reduced the sentiment_mod.py import time from 3.5 minutes to less than 30 seconds for me.,True
@Rochbenritter,2015-09-18T11:20:45Z,0,"Is it possible that pickle files can be corrupted? Because I get fast an answer for voted_classifier.classify(feats) [in my case: ""21328""], and then nothing (program is still running) ... How can I check if my pickle files are correct? (I would implement this checker in the sentiment_mod) - Or someone got an idea what else could be wrong?",True
@wijayanthaconsulations9390,2015-08-27T08:36:48Z,0,thank you sir.....finally i run it after watching your video series.but the problem is i always getting 1.0 for pos and neg.i expect a output value between 1 and 0 which according to sentence(how much positive and how much negative).can i do it with this code? please answer,True
@wijayanthaconsulations9390,2015-08-22T22:05:47Z,0,"getting a error like this please help....  Traceback (most recent call last):   File ""C:\Users\Sampath\Desktop\score1.py"", line 68, in <module>     pickle.dump(documents, save_classifier) NameError: name 'save_classifier' is not defined",True
@wijayanthaconsulations9390,2015-08-17T21:03:54Z,0,"i have run above code and getting a error like this   Traceback (most recent call last):   File ""C:\Users\Sampath\Desktop\score1.py"", line 68, in <module>     pickle.dump(documents, save_classifier) NameError: name 'save_classifier' is not defined",True
@wijayanthaconsulations9390,2015-08-15T12:06:52Z,0,it would be great if you can share the above code with us.,True
@jamielunn5869,2015-08-07T20:00:43Z,0,"Harrison, this tutorial series is amazing. Quick question: I noticed that if I write a sentence without any adjectives, the output is neg sentiment. Is this because some of the negative sample data contained a review without an adjective? Thank you!",True
@xPROxSNIPExMW2xPOWER,2015-07-31T08:03:21Z,0,Hey where do you write featuresets because It needs to be used by the module and when I checked it in the voteclassfier its not being written anywhere. Thanks.,True
@xPROxSNIPExMW2xPOWER,2015-07-30T05:10:55Z,0,Your website seems to be down currently. 7/30/2015,True
@Stefanslaapt,2015-07-26T20:28:47Z,0,"Can i use my sentimod.py on a text file? I.e. I have this csv file where i want to paste the neg/pos scores next to the corresponding sentences. If so, could you refer me to a source where this is explained? Keep up the good work man!",True
@friaamarwa9353,2015-07-14T02:48:37Z,0,"Hi , i thank you for this nice job , but i wanna to ask you about the picked files because i had this error : Traceback (most recent call last):        documents = pickle.load(documents_f)   File ""C:\Python27\lib\pickle.py"", line 1378, in load     return Unpickler(file).load()   File ""C:\Python27\lib\pickle.py"", line 857, in load     key = read(1) IOError: File not open for reading",True
@vishwampandya5103,2015-07-08T11:04:55Z,0,"sentdex Getting an error while running ""name ""ClassifierI"" is not defined""..............Please help ASAP",True
@vishwampandya5103,2015-07-05T19:00:59Z,0,sentdex How to do sentiment analysis on comments that we receive on Facebook or any other Social Network? How to get all the comments AUTOMATICALLY?,True
@shivrajacharjee6945,2015-06-29T13:52:59Z,0,"This is the result i got on running 'run_sentiment_mod.py': 10664 ('neg', 0.8) ('pos', 1.0) Weird. And Opposite of what was expected. What could have gone wrong? Any ideas? Thanks!",True
@sentdex,2015-05-22T17:28:51Z,6,"Mr. Temp Tempy, use the search on there, or go dashboard > data analysis > nltk.",True
@temptempy2083,2015-05-22T17:24:06Z,0,I can't see where the source code is posted for this video! Thanks.,True
@jhb3tube,2015-05-22T02:25:36Z,0,In the second part of the code we open the file featuresets. How did we get that file. I can't seem to create it.,True
@cliumay9,2015-05-20T13:54:29Z,0,"Hi Sentdex, Have you attempted to form a for loop for the classifiers(except the Voted one)? I have been trying using to from a dictionary for both the classifier and the string of it, but I got no result though. How will you build a for loop for the classifiers? Also, where can I find your source code? Where is it under? Thanks in advance. Good work!",True
@mahmoudhzade,2015-05-20T09:37:18Z,0,"Thank you so much, you help me a lot at my thesis.  God bless you.",True
@aikimark1955,2015-05-19T17:44:16Z,0,Where/why did the 10664 number get generated in the output?,True
